ARG PHP_VERSION=8.2
FROM php:${PHP_VERSION}-fpm-alpine as base

ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/

RUN chmod +x /usr/local/bin/install-php-extensions && \
    install-php-extensions xdebug apcu bcmath redis intl curl \
    mbstring iconv json openssl imap gmp calendar fileinfo pdo_pgsql imagick \
    gd

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

# https://getcomposer.org/doc/03-cli.md#composer-allow-superuser
ENV COMPOSER_ALLOW_SUPERUSER=1

# persistent / runtime deps
RUN apk add --no-cache git
RUN apk add --no-cache openssh

# alias for artisan
RUN echo '#! /bin/sh' >> /bin/art \
    && echo '/usr/local/bin/php /app/artisan "$@"' >> /bin/art \
    && chmod +x /bin/art

RUN echo '* * * * * su appuser -c "php /app/artisan schedule:run >> /dev/null 2>&1"' >> /etc/crontabs/root

FROM base AS app

ARG UID
ARG GID
ENV UID=${UID:-1000} GID=${GID:-1000}

RUN addgroup -g $GID appgroup && adduser -D -u $UID -G appgroup appuser && addgroup appuser www-data

WORKDIR /app

USER $UID

CMD php-fpm
