version: '3.8'

name: 'coach'

networks:
    default:

services:
    fpm: &app-container
        build:
            context: ./local
            dockerfile: Dockerfile_fpm
        container_name: ${PROJECT_NAME}_fpm
        networks:
            - default
        volumes:
            - &data-app ../:/app
            - ./local/config/fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
            - ./local/config/fpm/php.ini:/usr/local/etc/php/php.ini
            - ./local/config/fpm/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
        environment: &fpm-env
            PHP_IDE_CONFIG: serverName=docker-${PROJECT_NAME}
            REMOTE_HOST: host.docker.internal
            DB_HOST: postgres
            DB_DATABASE: &db-name app
            DB_USERNAME: &db-username root
            DB_PASSWORD: &db-password root
            APP_ENV: local
            HOME: /app
            UID: 1000
            GID: 1000
        depends_on:
            - postgres

    nginx:
        build:
            context: ./local
            dockerfile: Dockerfile_nginx
        container_name: ${PROJECT_NAME}_nginx
        ports:
            - 28694:80
        restart: always
        volumes:
            - *data-app
            - ./local/config/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./local/config/nginx/site.conf:/etc/nginx/site.conf
        networks:
            - default
        depends_on:
            - fpm

    postgres:
        image: postgis/postgis:14-3.2-alpine
        container_name: ${PROJECT_NAME}_db
        networks:
            - default
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
        environment:
            POSTGRES_DB: *db-name
            POSTGRES_USER: *db-username
            POSTGRES_PASSWORD: *db-password
        ports:
            - 9833:5432
        volumes:
            - ./dbdata:/var/lib/postgresql/data

    cron:
        <<: *app-container
        restart: always
        container_name: ${PROJECT_NAME}_cron
        user: root
        entrypoint: [ "crond", "-f" ]
        depends_on:
            - fpm
